version: "3.3"

services:
  consul:
    environment: 
      SNADDRESS: $(ip addr show eth0 | grep -o "inet [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*")
    build:
      context: .
      args: 
        OUR_SERVER_ADDRESS: ${SNADDRESS}
